try{
    let a;
    console.log(a.length);
    console.log("From inside");
}catch(e){
    console.log("Catch statement");
}
console.log("End");